// <auto-generated />
namespace WeekPlanner.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class rearrangedata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rearrangedata));
        
        string IMigrationMetadata.Id
        {
            get { return "201209191915153_rearrange data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
